export const productData = [
  {
    id: 1,
    name: "Giày nam 01",
    price: "1,800,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product12.jpg",
    amount: 1,
  },
  {
    id: 2,
    name: "Giày nam 02",
    price: "1,800,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product01.jpg",
    amount: 1,
  },
  {
    id: 3,
    name: "Giày nam 03",
    price: "1,800,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product02.jpg",
    amount: 1,
  },
  {
    id: 4,
    name: "Giày nam 04",
    price: "2,100,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product03.jpg",
    amount: 1,
  },
  {
    id: 5,
    name: "Giày nam 05",
    price: "1,900,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product04.jpg",
    amount: 1,
  },
  {
    id: 6,
    name: "Giày nam 06",
    price: "1,120,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product05.jpg",
    amount: 1,
  },
  {
    id: 7,
    name: "Giày nam 07",
    price: "1,260,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product06.jpg",
    amount: 1,
  },
  {
    id: 8,
    name: "Giày nam 08",
    price: "1,520,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product07.jpg",
    amount: 1,
  },
  {
    id: 9,
    name: "Giày nam 09",
    price: "1,200,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product08.jpg",
    amount: 1,
  },
  {
    id: 10,
    name: "Giày nam 10",
    price: "1,200,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product09.jpg",
    amount: 1,
  },
  {
    id: 11,
    name: "Giày nam 11",
    price: "1,300,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product10.jpg",
    amount: 1,
  },
  {
    id: 12,
    name: "Giày nam 12",
    price: "1,160,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product11.jpg",
    amount: 1,
  },

  //   nữ
  {
    id: 13,
    name: "Giày nữ  01",
    price: "1,800,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product12.jpg",
    amount: 1,
  },
  {
    id: 14,
    name: "Giày nữ 02",
    price: "1,800,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product01.jpg",
    amount: 1,
  },
  {
    id: 15,
    name: "Giày nữ 03",
    price: "1,800,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product02.jpg",
    amount: 1,
  },
  {
    id: 16,
    name: "Giày nữ 04",
    price: "2,100,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product03.jpg",
    amount: 1,
  },
  {
    id: 17,
    name: "Giày nữ 05",
    price: "1,900,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product04.jpg",
    amount: 1,
  },
  {
    id: 18,
    name: "Giày nữ 06",
    price: "1,120,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product05.jpg",
    amount: 1,
  },
  {
    id: 19,
    name: "Giày nữ 07",
    price: "1,260,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product06.jpg",
    amount: 1,
  },
  {
    id: 20,
    name: "Giày nữ 08",
    price: "1,520,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product07.jpg",
    amount: 1,
  },
  {
    id: 21,
    name: "Giày nữ 09",
    price: "1,200,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product08.jpg",
    amount: 1,
  },
  {
    id: 22,
    name: "Giày nữ 10",
    price: "1,200,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product09.jpg",
    amount: 1,
  },
  {
    id: 23,
    name: "Giày nữ 11",
    price: "1,300,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product10.jpg",
    amount: 1,
  },
  {
    id: 24,
    name: "Giày nữ 12",
    price: "1,160,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product11.jpg",
    amount: 1,
  },

  //trẻ con
  {
    id: 25,
    name: "Giày trẻ con 01",
    price: "1,800,000 ",
    category: "children",
    image: "./assets/img/Product/List-product/product13.jpg",
    amount: 1,
  },
  {
    id: 26,
    name: "Giày trẻ con 02",
    price: "1,800,000 ",
    category: "children",
    image: "./assets/img/Product/List-product/product14.jpg",
    amount: 1,
  },
  {
    id: 27,
    name: "Giày trẻ con 03",
    price: "1,800,000 ",
    category: "children",
    image: "./assets/img/Product/List-product/product15.jpg",
    amount: 1,
  },
  {
    id: 28,
    name: "Giày trẻ con 04",
    price: "2,100,000 ",
    category: "children",
    image: "./assets/img/Product/List-product/product16.jpg",
    amount: 1,
  },
  {
    id: 29,
    name: "Giày trẻ con 05",
    price: "1,900,000 ",
    category: "children",
    image: "./assets/img/Product/List-product/product17.jpg",
    amount: 1,
  },
  {
    id: 30,
    name: "Giày trẻ con 06",
    price: "1,900,000 ",
    category: "children",
    image: "./assets/img/Product/List-product/product18.jpg",
    amount: 1,
  },

  //   other
  {
    id: 31,
    name: "Phụ kiện khác 05",
    price: "1,900,000 ",
    category: "other",
    image: "./assets/img/other-product/img01.jpg",
    amount: 1,
  },
  {
    id: 32,
    name: "Phụ kiện khác 06",
    price: "1,120,000 ",
    category: "other",
    image: "./assets/img/other-product/img02.jpg",
    amount: 1,
  },
  {
    id: 33,
    name: "Phụ kiện khác 07",
    price: "1,260,000 ",
    category: "other",
    image: "./assets/img/other-product/img03.jpg",
    amount: 1,
  },
  {
    id: 34,
    name: "Phụ kiện khác 08",
    price: "1,520,000 ",
    category: "other",
    image: "./assets/img/other-product/img04.jpg",
    amount: 1,
  },
  {
    id: 35,
    name: "Phụ kiện khác 09",
    price: "1,200,000 ",
    category: "other",
    image: "./assets/img/other-product/img05.jpg",
    amount: 1,
  },
  {
    id: 36,
    name: "Phụ kiện khác 10",
    price: "1,200,000 ",
    category: "other",
    image: "./assets/img/other-product/img06.jpg",
    amount: 1,
  },
  {
    id: 37,
    name: "Phụ kiện khác 11",
    price: "1,300,000 ",
    category: "other",
    image: "./assets/img/other-product/img07.jpg",
    amount: 1,
  },
  {
    id: 38,
    name: "Phụ kiện khác 12",
    price: "1,160,000 ",
    category: "other",
    image: "./assets/img/other-product/img08.jpg",
    amount: 1,
  },
];
