export const productData = [
  {
    id: 1,
    name: "Nike Air Max",
    price: "1,800,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product12.jpg",
    amount: 1,
  },
  {
    id: 2,
    name: "Adidas Ultraboost",
    price: "1,800,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product01.jpg",
    amount: 1,
  },
  {
    id: 3,
    name: "New Balance 990",
    price: "1,800,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product02.jpg",
    amount: 1,
  },
  {
    id: 4,
    name: "Puma RS-X",
    price: "2,100,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product03.jpg",
    amount: 1,
  },
  {
    id: 5,
    name: "Reebok Classic Leather",
    price: "1,900,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product04.jpg",
    amount: 1,
  },
  {
    id: 6,
    name: "Vans Old Skool",
    price: "1,120,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product05.jpg",
    amount: 1,
  },
  {
    id: 7,
    name: "Converse Chuck Taylor All Star",
    price: "1,260,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product06.jpg",
    amount: 1,
  },
  {
    id: 8,
    name: "Under Armour Curry",
    price: "1,520,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product07.jpg",
    amount: 1,
  },
  {
    id: 9,
    name: "Brooks Ghost",
    price: "1,200,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product08.jpg",
    amount: 1,
  },
  {
    id: 10,
    name: "Asics Gel-Kayano",
    price: "1,200,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product09.jpg",
    amount: 1,
  },
  {
    id: 11,
    name: "Jordan Retro",
    price: "1,300,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product10.jpg",
    amount: 1,
  },
  {
    id: 12,
    name: "Saucony Jazz Original",
    price: "1,160,000 ",
    category: "man",
    image: "./assets/img/Product/List-product/product11.jpg",
    amount: 1,
  },

  //   nữ
  {
    id: 13,
    name: "Nike Air Force 1",
    price: "1,800,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product12.jpg",
    amount: 1,
  },
  {
    id: 14,
    name: "Adidas Superstar",
    price: "1,800,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product01.jpg",
    amount: 1,
  },
  {
    id: 15,
    name: "Puma Cali",
    price: "1,800,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product02.jpg",
    amount: 1,
  },
  {
    id: 16,
    name: "New Balance 574",
    price: "2,100,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product03.jpg",
    amount: 1,
  },
  {
    id: 17,
    name: "Reebok Club C",
    price: "1,900,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product04.jpg",
    amount: 1,
  },
  {
    id: 18,
    name: "Vans Authentic",
    price: "1,120,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product05.jpg",
    amount: 1,
  },
  {
    id: 19,
    name: "Converse Chuck Taylor All Star",
    price: "1,260,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product06.jpg",
    amount: 1,
  },
  {
    id: 20,
    name: "Under Armour HOVR",
    price: "1,520,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product07.jpg",
    amount: 1,
  },
  {
    id: 21,
    name: "Brooks Adrenaline GTS",
    price: "1,200,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product08.jpg",
    amount: 1,
  },
  {
    id: 22,
    name: "Asics Gel-Nimbus",
    price: "1,200,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product09.jpg",
    amount: 1,
  },
  {
    id: 23,
    name: "Skechers D'Lites",
    price: "1,300,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product10.jpg",
    amount: 1,
  },
  {
    id: 24,
    name: "Saucony Kinvara",
    price: "1,160,000 ",
    category: "woman",
    image: "./assets/img/Product/List-product/product11.jpg",
    amount: 1,
  },

  //trẻ con
  {
    id: 25,
    name: "Nike Revolution",
    price: "1,800,000 ",
    category: "children",
    image: "./assets/img/Product/List-product/product13.jpg",
    amount: 1,
  },
  {
    id: 26,
    name: "Adidas Superstar Foundation",
    price: "1,800,000 ",
    category: "children",
    image: "./assets/img/Product/List-product/product14.jpg",
    amount: 1,
  },
  {
    id: 27,
    name: "New Balance 680",
    price: "1,800,000 ",
    category: "children",
    image: "./assets/img/Product/List-product/product15.jpg",
    amount: 1,
  },
  {
    id: 28,
    name: "Puma Carson",
    price: "2,100,000 ",
    category: "children",
    image: "./assets/img/Product/List-product/product16.jpg",
    amount: 1,
  },
  {
    id: 29,
    name: "Reebok Rush Runner",
    price: "1,900,000 ",
    category: "children",
    image: "./assets/img/Product/List-product/product17.jpg",
    amount: 1,
  },
  {
    id: 30,
    name: "Vans Ward",
    price: "1,900,000 ",
    category: "children",
    image: "./assets/img/Product/List-product/product18.jpg",
    amount: 1,
  },

  //   other
  {
    id: 31,
    name: "Nike Elite Basketball Socks",
    price: "1,900,000 ",
    category: "other",
    image: "./assets/img/other-product/img01.jpg",
    amount: 1,
  },
  {
    id: 32,
    name: "Adidas Sport Duffel Bag",
    price: "1,120,000 ",
    category: "other",
    image: "./assets/img/other-product/img02.jpg",
    amount: 1,
  },
  {
    id: 33,
    name: "Under Armour Sweatband",
    price: "1,260,000 ",
    category: "other",
    image: "./assets/img/other-product/img03.jpg",
    amount: 1,
  },
  {
    id: 34,
    name: "Puma Running Hat",
    price: "1,520,000 ",
    category: "other",
    image: "./assets/img/other-product/img04.jpg",
    amount: 1,
  },
  {
    id: 35,
    name: "Reebok CrossFit Gloves",
    price: "1,200,000 ",
    category: "other",
    image: "./assets/img/other-product/img05.jpg",
    amount: 1,
  },
  {
    id: 36,
    name: "Vans Checkerboard Backpack",
    price: "1,200,000 ",
    category: "other",
    image: "./assets/img/other-product/img06.jpg",
    amount: 1,
  },
  {
    id: 37,
    name: "Converse Shoe Care Kit",
    price: "1,300,000 ",
    category: "other",
    image: "./assets/img/other-product/img07.jpg",
    amount: 1,
  },
  {
    id: 38,
    name: "Asics Headband",
    price: "1,160,000 ",
    category: "other",
    image: "./assets/img/other-product/img08.jpg",
    amount: 1,
  },
];
